### ISSUE TITLE
HA 2024.08 To Break This Integration?

### ISSUE THREAD

**Issue by ronaldheft** [slashback100/presence_simulation#139]
Looks like 2024.08 [will be removing light attributes from the history database](https://github.com/home-assistant/core/pull/121776). I assume this integration is dependent on that data to function.

**Comment by ronaldheft** [comment]
I reported this as an issue to HA core: https://github.com/home-assistant/core/issues/123028

**Comment by ronaldheft** [comment]
Unless other integrations can be identified that will break without light attributes, I think we'll need to plan for losing light attributes with 2024.8.

I haven't personally tested this integration with 2024.8 yet, but I'm assuming the main way this will break is lights will be turned back on at their previous brightness before the simulation started.

Is there anyway we could make this better? A few options I'm thinking of:
- Add new configuration option for default light attributes when a light support them (ex. color_temp and brightness)
- Listening to light events and storing the attribute data outside the HA database
- Providing an optional integration with InfluxDB, to use the light attributes persisted there, as an alternative to the recorder database

I would be willing to assist in implementing one or more of these options if there is interest.

Personally, I am leaning toward the InfluxDB option. Home Assistant has a native integration to store recorder history there, so there is a standard format to work with; it should only require writing the InfluxDB queries needed.

**Comment by woopstar** [comment]
Looks like it broke in 2024.8:

```
2024-08-07 22:14:10.438 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'presence_simulation': Unable to import component: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/presence_simulation/__init__.py", line 19, in <module>
    from homeassistant.components.recorder.const import DATA_INSTANCE
ImportError: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/presence_simulation/__init__.py", line 19, in <module>
    from homeassistant.components.recorder.const import DATA_INSTANCE
ImportError: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)
```

**Comment by slashback100** [comment]
Thanks I'll take a look asap

**Comment by slashback100** [comment]
Doesn't seem you are on the latest version of the integration. This line (import DATA_INSTANCE) has been removed quite some time ago.

**Comment by woopstar** [comment]
> Doesn't seem you are on the latest version of the integration. This line (import DATA_INSTANCE) has been removed quite some time ago.

You are right. HA did not say there was an update, but did a re-download and the error is gone. Maybe release a new version to be sure?

**Comment by ronaldheft** [comment]
I upgraded to 2024.8 and I haven't noticed anything broken with this integration, outside of the integration's inability to change brightness and color temperature of lights.

Here is the behavior I have observed:
* Lights will turn on at the previous brightness and color temperature before you started the simulation
* Lights can be [set at a different default using light profiles](https://www.home-assistant.io/integrations/light/)

I would still love to contribute an enhancement in the future to use InfluxDB as a data source, but for now, setting a default light value seems to be a decent workaround.

**Comment by slashback100** [comment]
Thanks for you test. I will close this issue then. 
An improvement could indeed be made with InfluxDB, but I personnaly really don't have any experience with it...
