### ISSUE TITLE
Error while presence switch to on 

### ISSUE THREAD

**Issue by matata86** [slashback100/presence_simulation#25]
Detaily protokolu (CHYBA)
 Tato chyba pochází z vlastní integrace.
Logger: homeassistant.core
Source: custom_components/presence_simulation/__init__.py:168
Integration: Presence Simulation (documentation, issues)
First occurred: 15. června 2021 20:51:45 (2 occurrences)
Last logged: 8:24:41

Error executing service: <ServiceCall presence_simulation.start (c:6fa0f6fc2b333141823d34da798c02ca)>
Error executing service: <ServiceCall presence_simulation.start (c:ab1a21a6d312152348a116658397d67f)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/presence_simulation/__init__.py", line 168, in handle_presence_simulation
    await entity.set_start_datetime(datetime.now(hass.config.time_zone))
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'

**Comment by slashback100** [comment]
Duplicate #24
