### ISSUE TITLE
Errors when starting after migrate to mariadb

### ISSUE THREAD

**Issue by mwright-git** [slashback100/presence_simulation#34]
Is there a problem using this integration when the history database has been migrated to mariadb?

I get the error(s) below when attempting to turn on presence simulation after I migrated my history database to mariadb.

ANy thoughts or ideas please?

`2021-09-09 13:45:33 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1517, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1498, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 192, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 99, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
2021-09-09 13:45:33 WARNING (MainThread) [homeassistant.components.history] get_significant_states was called from presence_simulation, this is a deprecated function. Use homeassistant.components.recorder.history.get_significant_states instead, please report this to the maintainer of presence_simulation
2021-09-09 13:45:33 ERROR (MainThread) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
[SQL: SELECT states.domain AS states_domain, states.entity_id AS states_entity_id, states.state AS states_state, states.attributes AS states_attributes, states.last_changed AS states_last_changed, states.last_updated AS states_last_updated 
FROM states 
WHERE states.last_updated > %s AND states.entity_id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ORDER BY states.entity_id, states.last_updated]
[parameters: (datetime.datetime(2021, 9, 2, 12, 45, 33, 391107, tzinfo=datetime.timezone.utc), 'light.dining_room_light', 'light.dining_room_lightstrip', 'light.hall_light', 'light.kitchen_light', 'light.landing_light', 'light.lounge_lightstrip', 'light.lounge_light', 'light.my_spa_lights', 'light.bedroom_lamp', 'light.cabinet_light', 'light.office_lamp', 'light.lounge_lamp')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2021-09-09 13:45:33 ERROR (MainThread) [homeassistant.components.recorder.util] Error executing query: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
2021-09-09 13:45:33 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall presence_simulation.start (c:369c78083b4ed29031db12b713d16c00)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/presence_simulation/__init__.py", line 184, in handle_presence_simulation
    dic = history.get_significant_states(hass=hass, start_time=minus_delta, entity_ids=expanded_entities, significant_changes_only=False)
  File "/usr/src/homeassistant/homeassistant/helpers/deprecation.py", line 110, in deprecated_func
    return func(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 63, in get_significant_states
    return history.get_significant_states(hass, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 66, in get_significant_states
    return _get_significant_states(hass, session, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 118, in _get_significant_states
    states = execute(
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 115, in execute
    result = list(qry)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/baked.py", line 382, in __iter__
    return self._iter().__iter__()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/baked.py", line 412, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 560, in _revalidate_connection
    self._invalid_transaction()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 532, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
2021-09-09 13:45:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'
Connected`

**Comment by slashback100** [comment]
I personally use it with mariadb so that should not be the problem

**Comment by slashback100** [comment]
fyi you are apparently not using the last version (you have a warning on get_significant_states)

**Comment by slashback100** [comment]
Try with the newest version please

**Comment by mwright-git** [comment]
I installed it using HACS which is not reporting an update being available.

**Comment by mwright-git** [comment]
Is it possible for you to fix it so that HACS sees version 1.5? I would rather update via HACS than install another version manually over it.

**Comment by slashback100** [comment]
1.5 is out.

**Comment by mwright-git** [comment]
I appreciate that - but HACS does not see it. According to HACS the latest version is 1.4

**Comment by slashback100** [comment]
It does for me...
![image](https://user-images.githubusercontent.com/43109757/135060798-a42f5239-e7ba-4ddc-8cd3-2759b40112fd.png)

**Comment by mwright-git** [comment]
It literally just showed the update a few minutes ago.

I have updated and I don't get any error messages when I turn it on. I will check if it is working later today.

Thanks
